version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: learn-ws-server
    ports:
      - "8081:8081"
    env_file:
      - ./server/.env.production
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: learn-ws-web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env.production
    restart: always
    depends_on:
      - server
